b = 3.4,5.6
a = "orleans is a very good good programmer"
print(a.capitalize())
print(a.casefold())
print(a.center(1))
print(a.count("good"))
print(a.encode())
print(a.endswith("programmer"))
print(a.expandtabs(5))
print(a.find("good"))
print(a.format("good"))
print(a.index("good"))
print(a.isalnum())
print(a.isalpha())
print(a.isdecimal())
print(a.isprintable())
print(a.istitle())
print(a.join("good "))
print(a.ljust(2))
print(a.title())
print(a.upper())
print(a.zfill(2))
print(a.partition(" "))